//! PKI Secret Engine (Phase 1).
//!
//! Pure-Rust X.509 stack — `rcgen` for DER assembly, RustCrypto under the
//! hood for primitives. No OpenSSL, no aws-lc-sys. Phase 2 will plug ML-DSA
//! signers behind the same `CertSigner` seam used here. See
//! [features/pki-secret-engine.md](../../../features/pki-secret-engine.md)
//! for the full design and roadmap.

use std::{any::Any, sync::Arc};

use derive_more::Deref;

use crate::{
    core::Core,
    errors::RvError,
    logical::{Backend, LogicalBackend, Path},
    modules::Module,
};

pub mod acme;
#[cfg(feature = "pki_pqc_composite")]
pub mod composite;
pub mod crypto;
pub mod csr;
pub mod issuers;
pub mod path_config;
pub mod path_intermediate;
pub mod path_issuers;
pub mod path_crl;
pub mod path_fetch;
pub mod path_issue;
pub mod path_revoke;
pub mod path_roles;
pub mod path_root;
pub mod path_tidy;
pub mod scheduler;
pub mod pqc;
pub mod storage;
pub mod x509;
#[cfg(feature = "pki_pqc_composite")]
pub mod x509_composite;
pub mod x509_pqc;

const PKI_BACKEND_HELP: &str = r#"
The PKI engine issues X.509 certificates against a self-managed CA. Phase 1
provides the classical algorithm set (RSA, ECDSA P-256/P-384, Ed25519) on a
pure-Rust stack. Post-quantum (ML-DSA) roles land in Phase 2.

The route surface is intentionally Vault-compatible so existing clients keep
working unchanged. Endpoints not yet implemented in Phase 1 return a clear
"unsupported operation" error rather than a 404.
"#;

pub struct PkiBackendInner {
    pub core: Arc<Core>,
}

#[derive(Deref)]
pub struct PkiBackend {
    #[deref]
    pub inner: Arc<PkiBackendInner>,
}

impl PkiBackend {
    pub fn new(core: Arc<Core>) -> Self {
        Self { inner: Arc::new(PkiBackendInner { core }) }
    }

    pub fn new_backend(&self) -> LogicalBackend {
        let paths: Vec<Path> = vec![
            self.roles_path(),
            self.roles_list_path(),
            self.root_generate_path(),
            self.root_sign_intermediate_path(),
            self.intermediate_generate_path(),
            self.intermediate_set_signed_path(),
            self.issue_path(),
            self.sign_path(),
            self.sign_verbatim_path(),
            self.tidy_path(),
            self.tidy_status_path(),
            self.config_auto_tidy_path(),
            self.fetch_cert_path(),
            self.fetch_ca_path(),
            self.fetch_ca_chain_path(),
            self.list_certs_path(),
            self.revoke_path(),
            self.crl_path(),
            self.crl_rotate_path(),
            self.issuer_crl_path(),
            self.issuers_list_path(),
            self.issuer_path(),
            self.config_issuers_path(),
            self.config_ca_path(),
            self.config_urls_path(),
            self.config_crl_path(),
            // ── ACME server endpoints (Phase 6.1 + 6.1.5) ──
            self.acme_config_path(),
            self.acme_directory_path(),
            self.acme_new_nonce_path(),
            self.acme_new_account_path(),
            self.acme_account_path(),
            self.acme_new_order_path(),
            self.acme_order_path(),
            self.acme_finalize_path(),
            self.acme_authz_path(),
            self.acme_chall_path(),
            self.acme_cert_path(),
        ];

        // The `new_logical_backend!` macro takes a literal path-list. We build
        // ours dynamically because there are 20 routes and several are
        // generated by helper methods on `PkiBackend`. The init step (which
        // compiles regexes) runs in `setup()`.
        let mut backend = LogicalBackend::new();
        for p in paths {
            backend.paths.push(Arc::new(p));
        }
        // ACME protocol endpoints are unauthenticated at the engine
        // layer — JWS in the request body is the auth.
        // `acme/config` stays authenticated (operator config, not
        // protocol surface).
        backend.unauth_paths = Arc::new(
            acme::UNAUTH_PATHS
                .iter()
                .map(|s| (*s).to_string())
                .collect(),
        );
        backend.help = PKI_BACKEND_HELP.to_string();
        backend
    }
}

pub struct PkiModule {
    pub name: String,
    pub backend: Arc<PkiBackend>,
}

impl PkiModule {
    pub fn new(core: Arc<Core>) -> Self {
        Self { name: "pki".to_string(), backend: Arc::new(PkiBackend::new(core)) }
    }
}

impl Module for PkiModule {
    fn name(&self) -> String {
        self.name.clone()
    }

    fn as_any_arc(self: Arc<Self>) -> Arc<dyn Any + Send + Sync> {
        self
    }

    fn setup(&self, core: &Core) -> Result<(), RvError> {
        let backend = self.backend.clone();
        let new_func = move |_c: Arc<Core>| -> Result<Arc<dyn Backend>, RvError> {
            let mut b = backend.new_backend();
            b.init()?;
            Ok(Arc::new(b))
        };
        core.add_logical_backend("pki", Arc::new(new_func))
    }

    fn cleanup(&self, core: &Core) -> Result<(), RvError> {
        core.delete_logical_backend("pki")
    }
}
