use std::{collections::HashMap, sync::Arc};

use super::{PkiBackend, PkiBackendInner};
use crate::{
    context::Context,
    errors::RvError,
    logical::{Backend, Field, FieldType, Operation, Path, PathOperation, Request, Response},
    new_fields, new_fields_internal, new_path, new_path_internal,
    storage::StorageEntry,
    utils::{cert, cert::CertBundle},
};

impl PkiBackend {
    pub fn config_ca_path(&self) -> Path {
        let pki_backend_ref = self.inner.clone();

        let path = new_path!({
            pattern: "config/ca",
            fields: {
                "pem_bundle": {
                    field_type: FieldType::Str,
                    description: "PEM-format, concatenated unencrypted secret key and certificate"
                }
            },
            operations: [
                {op: Operation::Write, handler: pki_backend_ref.write_path_ca}
            ],
            help: r#"
This configures the CA information used for credentials
generated by this backend. This must be a PEM-format, concatenated
unencrypted secret key and certificate.

For security reasons, you can only view the certificate when reading this endpoint
                        "#
        });

        path
    }
}

#[maybe_async::maybe_async]
impl PkiBackendInner {
    pub async fn write_path_ca(&self, _backend: &dyn Backend, req: &mut Request) -> Result<Option<Response>, RvError> {
        let pem_bundle_value = req.get_data("pem_bundle")?;
        let pem_bundle = pem_bundle_value.as_str().ok_or(RvError::ErrRequestFieldInvalid)?;
        let cert_bundle = cert::cert_bundle_from_pem_bundle(pem_bundle)?;

        cert_bundle.verify()?;

        self.store_ca_bundle(req, &cert_bundle).await?;

        let entry = StorageEntry { key: "crl".to_string(), value: Vec::new() };

        req.storage_put(&entry).await?;

        Ok(None)
    }

    pub async fn fetch_ca_bundle(&self, req: &Request) -> Result<CertBundle, RvError> {
        let entry = req.storage_get("config/ca_bundle").await?;
        if entry.is_none() {
            return Err(RvError::ErrPkiCaNotConfig);
        }

        let ca_bundle: CertBundle = serde_json::from_slice(entry.unwrap().value.as_slice())?;
        Ok(ca_bundle)
    }

    pub async fn store_ca_bundle(&self, req: &mut Request, ca_bundle: &CertBundle) -> Result<(), RvError> {
        let mut entry = StorageEntry::new("config/ca_bundle", ca_bundle)?;

        req.storage_put(&entry).await?;

        entry.key = "ca".to_string();
        entry.value = ca_bundle.certificate.to_pem().unwrap();
        req.storage_put(&entry).await?;

        let serial_number_hex = ca_bundle.serial_number.replace(':', "-").to_lowercase();
        self.store_cert_der(req, &serial_number_hex, ca_bundle.certificate.to_der()?).await?;

        Ok(())
    }

    pub async fn delete_ca_bundle(&self, req: &Request) -> Result<(), RvError> {
        let ca_bundle = self.fetch_ca_bundle(req).await?;
        let serial_number_hex = ca_bundle.serial_number.replace(':', "-").to_lowercase();

        self.delete_cert(req, &serial_number_hex).await?;

        req.storage_delete("config/ca_bundle").await?;

        Ok(())
    }
}
