// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AttestRequest {
    #[prost(oneof = "attest_request::Phase", tags = "1, 2, 3")]
    pub phase: ::core::option::Option<attest_request::Phase>,
}
/// Nested message and enum types in `AttestRequest`.
pub mod attest_request {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Phase {
        #[prost(message, tag = "1")]
        Init(super::AttestInit),
        #[prost(message, tag = "2")]
        ChallengeResponse(super::ChallengeResponse),
        #[prost(message, tag = "3")]
        Csr(super::Csr),
    }
}
/// Phase 2 — hardware and boot attestation evidence.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AttestInit {
    /// DER EK certificate
    #[prost(bytes = "vec", tag = "1")]
    pub ek_cert: ::prost::alloc::vec::Vec<u8>,
    /// DER intermediate CA certs
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub ek_intermediates: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// marshaled TPMT_PUBLIC
    #[prost(bytes = "vec", tag = "3")]
    pub aik_pub: ::prost::alloc::vec::Vec<u8>,
    /// marshaled TPMS_ATTEST
    #[prost(bytes = "vec", tag = "4")]
    pub quote_blob: ::prost::alloc::vec::Vec<u8>,
    /// marshaled TPMT_SIGNATURE
    #[prost(bytes = "vec", tag = "5")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    /// raw PCR values for digest recompute
    #[prost(message, repeated, tag = "6")]
    pub pcr_values: ::prost::alloc::vec::Vec<PcrValue>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PcrValue {
    #[prost(uint32, tag = "1")]
    pub index: u32,
    #[prost(bytes = "vec", tag = "2")]
    pub value: ::prost::alloc::vec::Vec<u8>,
}
/// Phase 3 — the secret released by TPM2_ActivateCredential.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChallengeResponse {
    #[prost(bytes = "vec", tag = "1")]
    pub secret: ::prost::alloc::vec::Vec<u8>,
}
/// Phase 4 — TPM-bound composite CSR.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Csr {
    /// concat composite public key (1984 bytes)
    #[prost(bytes = "vec", tag = "1")]
    pub composite_pub: ::prost::alloc::vec::Vec<u8>,
    /// DPoP key thumbprint, base64url
    #[prost(string, tag = "2")]
    pub dpop_jkt: ::prost::alloc::string::String,
    /// AIK signature over SHA-384(composite_pub)
    #[prost(bytes = "vec", tag = "3")]
    pub aik_sig: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AttestResponse {
    #[prost(oneof = "attest_response::Phase", tags = "1, 2, 3")]
    pub phase: ::core::option::Option<attest_response::Phase>,
}
/// Nested message and enum types in `AttestResponse`.
pub mod attest_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Phase {
        #[prost(message, tag = "1")]
        Nonce(super::Nonce),
        #[prost(message, tag = "2")]
        Challenge(super::Challenge),
        #[prost(message, tag = "3")]
        Svid(super::SvidBundle),
    }
}
/// Phase 2 — server-supplied qualifyingData for the quote.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Nonce {
    #[prost(bytes = "vec", tag = "1")]
    pub nonce: ::prost::alloc::vec::Vec<u8>,
}
/// Phase 3 — credential-activation challenge (MakeCredential output).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Challenge {
    #[prost(bytes = "vec", tag = "1")]
    pub credential_blob: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub secret_blob: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SvidBundle {
    /// compact JWS SVID
    #[prost(string, tag = "1")]
    pub jws: ::prost::alloc::string::String,
    /// unix seconds (iat)
    #[prost(int64, tag = "2")]
    pub issued_at: i64,
    /// unix seconds (exp)
    #[prost(int64, tag = "3")]
    pub expires_at: i64,
    /// sub claim, for convenience
    #[prost(string, tag = "4")]
    pub spiffe_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FetchRequest {
    #[prost(string, tag = "1")]
    pub spiffe_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RotateRequest {
    /// the JWS to renew
    #[prost(string, tag = "1")]
    pub current_svid: ::prost::alloc::string::String,
    /// current PCRs, for drift detection
    #[prost(message, repeated, tag = "2")]
    pub pcr_values: ::prost::alloc::vec::Vec<PcrValue>,
    /// policy epoch the client believes is live
    #[prost(uint64, tag = "3")]
    pub known_epoch: u64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct JwksRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JwksResponse {
    #[prost(string, tag = "1")]
    pub jwks_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RevokeSvidRequest {
    /// lowercase hex SHA-384 of the compact JWS (96 chars)
    #[prost(string, tag = "1")]
    pub cert_sha: ::prost::alloc::string::String,
    /// stable operator opcode, e.g. "key-compromise"
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RevokeHostRequest {
    /// host SPIFFE id to revoke
    #[prost(string, tag = "1")]
    pub spiffe_id: ::prost::alloc::string::String,
    /// stable operator opcode
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RevokeResponse {
    /// sequence number of the CRL carrying the revocation
    #[prost(uint64, tag = "1")]
    pub crl_number: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BumpEpochRequest {
    /// stable operator opcode, e.g. "rim-policy-change"
    #[prost(string, tag = "1")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct BumpEpochResponse {
    /// the epoch now in force after the bump
    #[prost(uint64, tag = "1")]
    pub new_epoch: u64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListSvidsRequest {}
/// Compact view of one issued SVID — never the private material, just enough
/// for an operator to identify a host and act on it.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SvidSummary {
    /// subject SPIFFE id
    #[prost(string, tag = "1")]
    pub spiffe_id: ::prost::alloc::string::String,
    /// lowercase hex SHA-384 of the compact JWS (RevokeSvid key)
    #[prost(string, tag = "2")]
    pub cert_sha: ::prost::alloc::string::String,
    /// unix seconds (iat) of the current bundle
    #[prost(int64, tag = "3")]
    pub issued_at: i64,
    /// unix seconds (exp) of the current bundle
    #[prost(int64, tag = "4")]
    pub expires_at: i64,
    /// RIM policy generation at the last full attestation
    #[prost(string, tag = "5")]
    pub policy_id: ::prost::alloc::string::String,
    /// RIM policy epoch at the last full attestation
    #[prost(uint64, tag = "6")]
    pub policy_epoch: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListSvidsResponse {
    #[prost(message, repeated, tag = "1")]
    pub svids: ::prost::alloc::vec::Vec<SvidSummary>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignedTreeHead {
    /// canonical CBOR of ferro_audit::SthBody
    #[prost(bytes = "vec", tag = "1")]
    pub body_cbor: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub signer_kid: ::prost::alloc::string::String,
    /// composite Ed25519+ML-DSA-65 concat
    #[prost(bytes = "vec", tag = "3")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct LatestSthRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LatestSthResponse {
    #[prost(message, optional, tag = "1")]
    pub sth: ::core::option::Option<SignedTreeHead>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct InclusionProofRequest {
    #[prost(uint64, tag = "1")]
    pub leaf_index: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InclusionProofResponse {
    /// 48-byte SHA3-384
    #[prost(bytes = "vec", tag = "1")]
    pub leaf_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "2")]
    pub leaf_index: u64,
    #[prost(uint64, tag = "3")]
    pub tree_size: u64,
    /// 48-byte SHA3-384
    #[prost(bytes = "vec", tag = "4")]
    pub root_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", repeated, tag = "5")]
    pub audit_path: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ConsistencyProofRequest {
    #[prost(uint64, tag = "1")]
    pub old_size: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConsistencyProofResponse {
    #[prost(uint64, tag = "1")]
    pub old_size: u64,
    #[prost(uint64, tag = "2")]
    pub new_size: u64,
    #[prost(bytes = "vec", tag = "3")]
    pub new_root_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", repeated, tag = "4")]
    pub audit_path: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AppendAuditRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub event_cbor: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AppendAuditResponse {
    #[prost(uint64, tag = "1")]
    pub leaf_index: u64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HealthRequest {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HealthResponse {
    /// True iff the local node believes it can serve. A non-clustered CMIS is
    /// always healthy; a clustered CMIS is healthy iff hiqlite reports its local
    /// node is up and synced.
    #[prost(bool, tag = "1")]
    pub healthy: bool,
    /// Raft role of the local node. `NODE_ROLE_UNKNOWN` for non-clustered nodes
    /// or while the cluster is transitioning.
    #[prost(enumeration = "NodeRole", tag = "2")]
    pub role: i32,
    /// Local node id. `0` for non-clustered nodes.
    #[prost(uint64, tag = "3")]
    pub node_id: u64,
}
/// Coarse Raft role classification — matches `ferro_raft::NodeRole` but is
/// pinned in the wire schema independently.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum NodeRole {
    Unknown = 0,
    Leader = 1,
    Follower = 2,
    Learner = 3,
}
impl NodeRole {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "NODE_ROLE_UNKNOWN",
            Self::Leader => "NODE_ROLE_LEADER",
            Self::Follower => "NODE_ROLE_FOLLOWER",
            Self::Learner => "NODE_ROLE_LEARNER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NODE_ROLE_UNKNOWN" => Some(Self::Unknown),
            "NODE_ROLE_LEADER" => Some(Self::Leader),
            "NODE_ROLE_FOLLOWER" => Some(Self::Follower),
            "NODE_ROLE_LEARNER" => Some(Self::Learner),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod machine_identity_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct MachineIdentityClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl<T> MachineIdentityClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> MachineIdentityClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            MachineIdentityClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Four-phase streaming attestation handshake. The server speaks first with
        /// a Nonce, then drives challenge/response and finally returns the SVID.
        pub async fn attest(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::AttestRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::AttestResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ferrogate.v1.MachineIdentity/Attest",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("ferrogate.v1.MachineIdentity", "Attest"));
            self.inner.streaming(req, path, codec).await
        }
        /// Fetch the most recently issued SVID for a SPIFFE id (debug / cache miss).
        pub async fn fetch_svid(
            &mut self,
            request: impl tonic::IntoRequest<super::FetchRequest>,
        ) -> std::result::Result<tonic::Response<super::SvidBundle>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ferrogate.v1.MachineIdentity/FetchSVID",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("ferrogate.v1.MachineIdentity", "FetchSVID"));
            self.inner.unary(req, path, codec).await
        }
        /// In-window renewal. No TPM interaction when PCRs and policy epoch are
        /// unchanged and the SVID is inside its re-attestation window; otherwise the
        /// server refuses and the client must run a full Attest.
        pub async fn rotate(
            &mut self,
            request: impl tonic::IntoRequest<super::RotateRequest>,
        ) -> std::result::Result<tonic::Response<super::SvidBundle>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ferrogate.v1.MachineIdentity/Rotate",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("ferrogate.v1.MachineIdentity", "Rotate"));
            self.inner.unary(req, path, codec).await
        }
        /// Composite verification key set used to validate SVID signatures. Also
        /// carries the composite-signed CRL in the `x-ferrogate-crl` extension member
        /// (feature F11).
        pub async fn jwks(
            &mut self,
            request: impl tonic::IntoRequest<super::JwksRequest>,
        ) -> std::result::Result<tonic::Response<super::JwksResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ferrogate.v1.MachineIdentity/JWKS",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("ferrogate.v1.MachineIdentity", "JWKS"));
            self.inner.unary(req, path, codec).await
        }
        /// Admin RPC: revoke a single SVID by the lowercase-hex SHA-384 of its compact
        /// JWS. The revocation appears in the next published CRL (CMIS publishes
        /// immediately on revoke). Authenticated out of band as an operator action.
        pub async fn revoke_svid(
            &mut self,
            request: impl tonic::IntoRequest<super::RevokeSvidRequest>,
        ) -> std::result::Result<tonic::Response<super::RevokeResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ferrogate.v1.MachineIdentity/RevokeSvid",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("ferrogate.v1.MachineIdentity", "RevokeSvid"));
            self.inner.unary(req, path, codec).await
        }
        /// Admin RPC: revoke every SVID and child token for a host SPIFFE ID.
        pub async fn revoke_host(
            &mut self,
            request: impl tonic::IntoRequest<super::RevokeHostRequest>,
        ) -> std::result::Result<tonic::Response<super::RevokeResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ferrogate.v1.MachineIdentity/RevokeHost",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("ferrogate.v1.MachineIdentity", "RevokeHost"));
            self.inner.unary(req, path, codec).await
        }
        /// Admin RPC: bump the live RIM policy epoch (feature F10). Every host whose
        /// last full attestation was under the previous epoch is forced through a
        /// fresh four-phase Attest at its next Rotate. Records a PolicyEpochBumped
        /// audit event. Authenticated out of band as an operator action.
        pub async fn bump_epoch(
            &mut self,
            request: impl tonic::IntoRequest<super::BumpEpochRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BumpEpochResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ferrogate.v1.MachineIdentity/BumpEpoch",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("ferrogate.v1.MachineIdentity", "BumpEpoch"));
            self.inner.unary(req, path, codec).await
        }
        /// Admin RPC: enumerate the issued SVIDs this node knows about — the local
        /// store on a single replica, or the full clustered set on an HA deployment.
        /// Returns a compact summary per SVID, including the `cert_sha` an operator
        /// can feed straight into RevokeSvid. Authenticated out of band as an
        /// operator action.
        pub async fn list_svids(
            &mut self,
            request: impl tonic::IntoRequest<super::ListSvidsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListSvidsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ferrogate.v1.MachineIdentity/ListSvids",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("ferrogate.v1.MachineIdentity", "ListSvids"));
            self.inner.unary(req, path, codec).await
        }
        /// Latest Signed Tree Head. Verifiers re-anchor incremental consistency
        /// proofs against this.
        pub async fn latest_sth(
            &mut self,
            request: impl tonic::IntoRequest<super::LatestSthRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LatestSthResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ferrogate.v1.MachineIdentity/LatestSth",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("ferrogate.v1.MachineIdentity", "LatestSth"));
            self.inner.unary(req, path, codec).await
        }
        /// RFC 6962 inclusion proof for the leaf at `leaf_index` against the
        /// current tree.
        pub async fn inclusion_proof(
            &mut self,
            request: impl tonic::IntoRequest<super::InclusionProofRequest>,
        ) -> std::result::Result<
            tonic::Response<super::InclusionProofResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ferrogate.v1.MachineIdentity/InclusionProof",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("ferrogate.v1.MachineIdentity", "InclusionProof"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// RFC 6962 consistency proof from `old_size` to the current tree size.
        pub async fn consistency_proof(
            &mut self,
            request: impl tonic::IntoRequest<super::ConsistencyProofRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ConsistencyProofResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ferrogate.v1.MachineIdentity/ConsistencyProof",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("ferrogate.v1.MachineIdentity", "ConsistencyProof"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// MIA-originated event forwarder. The body is canonical CBOR of a
        /// `ferro_audit::AuditEvent`; CMIS appends it to its log and returns the
        /// assigned leaf index.
        pub async fn append_audit_event(
            &mut self,
            request: impl tonic::IntoRequest<super::AppendAuditRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AppendAuditResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ferrogate.v1.MachineIdentity/AppendAuditEvent",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("ferrogate.v1.MachineIdentity", "AppendAuditEvent"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Coarse readiness probe for L4/L7 load balancers. Reports the local node's
        /// Raft role and a single `healthy` boolean — an LB should treat `Unknown`
        /// and `!healthy` alike as "not ready".
        pub async fn health(
            &mut self,
            request: impl tonic::IntoRequest<super::HealthRequest>,
        ) -> std::result::Result<tonic::Response<super::HealthResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ferrogate.v1.MachineIdentity/Health",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("ferrogate.v1.MachineIdentity", "Health"));
            self.inner.unary(req, path, codec).await
        }
    }
}
