use std::path::Path;

#[path = "build_support/app_commands.rs"]
mod app_commands;

/// The permission set granting every registered app command, generated
/// below from the `generate_handler!` list. `capabilities/default.json`
/// grants it to `main` (and `plugin-*`), which is what keeps those windows'
/// command surface exactly what it was before the app had an ACL manifest.
const ALL_COMMANDS_SET: &str = "app-all-commands";
const ALL_COMMANDS_SET_FILE: &str = "permissions/generated/app-all-commands.json";

fn main() {
    // The `tauri-plugin-mcp-bridge` plugin is feature-gated behind
    // `mcp_local_dev` (see CLAUDE.md / agent.md "Local Tauri MCP
    // Bridge"). When the feature is *off*, the plugin isn't compiled
    // in and its permission schema (`mcp-bridge:default`) isn't
    // discoverable — referencing it from a capability file would
    // fail the Tauri build. So the bridge's capability lives in a
    // separate file that we materialize only under the dev feature
    // and delete otherwise, keeping a single source of truth in this
    // crate.
    let cap_path = Path::new("capabilities").join("mcp-bridge.json");
    if cfg!(feature = "mcp_local_dev") {
        let body = r#"{
  "$schema": "https://raw.githubusercontent.com/nicerdicer/tauri-docs/refs/heads/v2/tooling/cli/schema.json",
  "identifier": "mcp-bridge",
  "description": "Local Tauri MCP bridge — dev-only. Gated by the `mcp_local_dev` Cargo feature and `BASTION_TAURI_MCP=1` at runtime.",
  "local": true,
  "windows": ["main", "ssh-*", "rdp-*"],
  "permissions": ["mcp-bridge:default"]
}
"#;
        // Write only if contents differ so we don't bump mtime and
        // re-run Tauri's permission resolver on every build.
        write_if_changed(&cap_path, body);
    } else if cap_path.exists() {
        std::fs::remove_file(&cap_path).expect("remove stale mcp-bridge capability");
    }
    println!("cargo:rerun-if-changed=build.rs");

    // Per-window app-command ACL (T110, features/session-workspace.md).
    //
    // Handing Tauri an app manifest turns its ACL on for *app* commands:
    // from then on a webview may call a command only if a capability that
    // matches its window grants `allow-<command>`. Without one, any local
    // webview could call every command — which is how the session windows
    // and the Session Workspace reached the whole vault API. The commands
    // are read from the `generate_handler!` list so the manifest cannot
    // drift from what is registered; see build_support/app_commands.rs.
    println!("cargo:rerun-if-changed=src/lib.rs");
    println!("cargo:rerun-if-changed=build_support/app_commands.rs");
    let lib_rs = std::fs::read_to_string("src/lib.rs").expect("read src/lib.rs");
    let commands = app_commands::registered_commands(&lib_rs)
        .unwrap_or_else(|e| panic!("reading the app command list for the ACL manifest: {e}"));

    // Every registered command, as one set, for the windows that keep the
    // full surface. Generated (and gitignored) so a new command can never
    // be missing from it.
    // Written by hand rather than with serde_json (not a build-dependency):
    // `registered_commands` admits only `[a-z0-9_]` names, so nothing
    // needs escaping.
    let allows: Vec<String> =
        commands.iter().map(|c| format!("        \"{}\"", app_commands::allow_permission(c))).collect();
    let set = format!(
        "{{\n  \"set\": [\n    {{\n      \"identifier\": \"{ALL_COMMANDS_SET}\",\n      \"description\": \"Every app \
         command this build registers. Generated by build.rs from the generate_handler! list in src/lib.rs - do \
         not edit. Granted to the main window and plugin windows only.\",\n      \"permissions\": [\n{}\n      \
         ]\n    }}\n  ]\n}}\n",
        allows.join(",\n")
    );
    let set_path = Path::new(ALL_COMMANDS_SET_FILE);
    std::fs::create_dir_all(set_path.parent().expect("set file has a parent")).expect("create permissions/generated");
    write_if_changed(set_path, &set);

    // `AppManifest::commands` wants `&'static`; a build script runs once,
    // so leaking the list is the simplest way to provide it.
    let commands: &'static [&'static str] =
        Box::leak(commands.into_iter().map(|c| &*Box::leak(c.into_boxed_str())).collect::<Vec<_>>().into_boxed_slice());
    let attributes = tauri_build::Attributes::new().app_manifest(tauri_build::AppManifest::new().commands(commands));
    if let Err(error) = tauri_build::try_build(attributes) {
        // Same reporting as `tauri_build::build()`.
        println!("{error:#}");
        std::process::exit(1);
    }
}

fn write_if_changed(path: &Path, body: &str) {
    let needs_write = match std::fs::read_to_string(path) {
        Ok(existing) => existing != body,
        Err(_) => true,
    };
    if needs_write {
        std::fs::write(path, body).unwrap_or_else(|e| panic!("write {}: {e}", path.display()));
    }
}
